### ISSUE TITLE
Pre-trained weights not available

### ISSUE THREAD

**Issue by maheshreddy24** [lalithbharadwajbaru/Wavelet-CLIP#3]
I attempted to implement the project but couldn't locate the pre-trained model weights. Could you please update the README file with the appropriate links to the weights?

**Comment by Rohit-Boddeda** [comment]
Dear @maheshr24, thank you for bringing this to our attention! We apologize for any inconvenience. We've updated the README with links to the pre-trained model weights. Please take a look, and let us know if you have any further questions.
