### ISSUE TITLE
Pretrained weights not working

### ISSUE THREAD

**Issue by flicht** [lalithbharadwajbaru/Wavelet-CLIP#5]
I've downloaded the code and downloaded the pretrained weights and put them in `./training/weights/`

`clip_wavehead_ckpt_best.pth`
`clip_ckpt_best.pth`

Then when I run:

`python3 training/gen_test.py --detector_path ./training/config/detector/detector.yaml --test_dataset "DDIM" "DDPM" "LDM" --weights_path ./training/weights/clip_wavehead_ckpt_best.pth`

I get the following error:

`===> Load checkpoint from: ./training/weights/clip_wavelet_best.pth
Traceback (most recent call last):
  File "./Wavelet-CLIP/training/gen_test.py", line 283, in <module>
    main()
  File "./Wavelet-CLIP/training/gen_test.py", line 272, in main
    model.load_state_dict(state_dict, strict=True)
  File "~/.pyenv/versions/wvlet-clip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for CLIPDetectorWavelet:
	Unexpected key(s) in state_dict: "backbone.embeddings.position_ids".`

It seems like the weights are different from what the model is expecting?

**Comment by lalithbharadwajbaru** [comment]
Dear @flicht,  

Thank you for reaching out.  

We have reviewed the code thoroughly, created a fresh conda environment, and successfully executed the file. Based on our findings, if you set up the environment precisely as outlined in the `README.md` file and fulfill the requirements using the specified library versions in `install.sh`, the issue should not persist.  

We kindly request you to attempt running the code again by creating a new Conda environment and strictly following the provided instructions. If the issue continue to arise, we would greatly appreciate it if you could share additional details to help us better understand and resolve the problem.  

Please do not hesitate to let us know if there is anything further we can assist you with.  

Kind Regards
Lalith

**Comment by flicht** [comment]
Thanks, I had to do a bit of troubleshooting and some additional steps to get it running.

I did a fresh install on:
`ubuntu 20.04`
`CUDA Version: 11.4`
`Tesla T4`

1. Fresh install of miniforge.

2. Clone the repo.

3. Create conda env
`conda create -n wavelet python=3.7.2` (I got the python version from DeepFakeBench)
4. Activate environment
5. Install dependencies `sh install.sh` (There were a few warnings and errors e.g. `ERROR: No matching distribution found for pandas==1.4.2, ERROR: No matching distribution found for install`- ignore for now)


6. Download weights from your [URL](https://mega.nz/folder/2BMQ0RJK#h_0M09W5GWXKWZvEE7fxOg). 
7. Rename the weights from `clip_wavehead_ckpt_best.pth` to `clip_wavelet_best.pth` (To match your later instructions) and put them in `training/weights`
8. Download Datasets from the [URL](https://mega.nz/folder/KdElBYaJ#nPuF06k5ma1FCf97ypnD5g)
9. Don't put the datasets in `datasets` (despite readme). Put them in `sampled_celebahq_50K`

10.Run command example command 
```
python3 training/gen_test.py --detector_path ./training/config/detector/detector.yaml --test_dataset "DDIM" "DDPM" "LDM" --weights_path ./training/weights/clip_wavelet_best.pth
```

11. If you get error `ModuleNotFoundError: No module named 'pytorch_wavelets'` -> `pip install pytorch_wavelets`
12. Should work!

**Comment by lalithbharadwajbaru** [comment]
Dear @flicht,

Thank you for your effort and the detailed breakdown of the steps and challenges you encountered while executing our code. We are closing the issue and will certainly incorporate the necessary changes to ensure smoother execution moving forward.

Kind regards,
Lalith
